etypes = [
    "aes128-cts-hmac-sha1-96",
    "aes256-cts-hmac-sha1-96",
]
max_ticket_lifetime = "1w"
max_renewable_lifetime = "1m"
domains = [
    "informis.land",
]
kdc_role = "kdc"
trusts = [
    "FUDO.ORG",
    "SEA.FUDO.ORG",
]

[principals."WELLKNOWN/ANONYMOUS@INFORMIS.LAND"]
kind = "infrastructure"

[principals."WELLKNOWN/org.h5l.fast-cookie@WELLKNOWN:ORG.H5L"]
kind = "infrastructure"

[principals."changepw/kerberos@INFORMIS.LAND"]
kind = "infrastructure"

[principals."default@INFORMIS.LAND"]
kind = "infrastructure"

[principals."host/locum.informis.land"]
kind = "service"

[principals."host/procul.informis.land"]
kind = "service"

[principals."kadmin/admin@INFORMIS.LAND"]
kind = "infrastructure"

[principals."kadmin/changepw@INFORMIS.LAND"]
kind = "infrastructure"

[principals."kadmin/hprop@INFORMIS.LAND"]
kind = "infrastructure"

[principals."krbtgt/FUDO.ORG@INFORMIS.LAND"]
kind = "cross-realm"
peer = "FUDO.ORG"

[principals."krbtgt/INFORMIS.LAND@FUDO.ORG"]
kind = "cross-realm"
peer = "FUDO.ORG"

[principals."krbtgt/INFORMIS.LAND@INFORMIS.LAND"]
kind = "infrastructure"

[principals."krbtgt/INFORMIS.LAND@SEA.FUDO.ORG"]
kind = "cross-realm"
peer = "SEA.FUDO.ORG"

[principals."krbtgt/SEA.FUDO.ORG@INFORMIS.LAND"]
kind = "cross-realm"
peer = "SEA.FUDO.ORG"

[principals."nfs/locum.informis.land"]
kind = "service"

[principals."nfs/procul.informis.land"]
kind = "service"

[principals."postgres/locum.informis.land"]
kind = "service"

[principals."postgres/procul.informis.land"]
kind = "service"

[principals."ssh/locum.informis.land"]
kind = "service"

[principals."ssh/procul.informis.land"]
kind = "service"
