services = [
    "host",
    "ssh",
    "nfs",
]
filesystem_keys = []
age_pubkey = "age1s8n5urw78csvsgcxmwplfe4kmr6w3urnud6932v7j658gmmmfdgsq4kpq4"

[extra_secrets]

[placement.nexus-key]
target = "/run/aegis/nexus-key"
user = "root"
group = "root"
mode = "0400"

[placement.ssh-host-keys]
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
