services = [
    "host",
    "ssh",
]
filesystem_keys = []
age_pubkey = "age17698sjx37ta9kpc9gx3v5k9656mmx5emv8ffj7g35tv3un8x7uas9h50pf"

[extra_secrets]

[placement.ssh-host-keys]
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
