[secrets."gpu-node-tagger.ca-crt"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.ca-crt.age"
target = "/run/gpu-node-tagger/ca.crt"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"

[secrets."gpu-node-tagger.token"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.token.age"
target = "/run/gpu-node-tagger/token"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"
