[secrets.nebula-fudo-cert]
source = "nebula/fudo.crt.age"
target = "/run/aegis/nebula/fudo.crt"
user = "nebula-fudo"
group = "nebula-fudo"
mode = "0444"

[secrets.nebula-fudo-ca]
source = "nebula/fudo-ca.crt.age"
target = "/run/aegis/nebula/fudo-ca.crt"
user = "nebula-fudo"
group = "nebula-fudo"
mode = "0444"
