roles = [
    "domain-burg.fudo.org",
    "domain-sea.fudo.org",
    "site-seattle",
    "site-thecitadel",
]

[[ssh-host-keys]]
source = "ssh/ssh_host_ecdsa_key.age"
target = "ssh_host_ecdsa_key"
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
type = "ecdsa"

[[ssh-host-keys]]
source = "ssh/ssh_host_ed25519_key.age"
target = "ssh_host_ed25519_key"
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
type = "ed25519"

[keytab]
source = "keytab.age"
target = "/run/aegis/keytab"
user = "root"
group = "root"
mode = "0600"

[nexus-key]
source = "nexus-key.age"
target = "/run/aegis/nexus-key"
user = "root"
group = "root"
mode = "0400"

[secrets.nebula-fudo-cert]
source = "nebula/fudo.crt.age"
target = "/run/aegis/nebula/fudo.crt"
user = "nebula-fudo"
group = "nebula-fudo"
mode = "0444"

[secrets.nebula-fudo-ca]
source = "nebula/fudo-ca.crt.age"
target = "/run/aegis/nebula/fudo-ca.crt"
user = "nebula-fudo"
group = "nebula-fudo"
mode = "0444"

[secrets.nebula-fudo-key]
source = "nebula/fudo.key.age"
target = "/run/aegis/nebula/fudo.key"
user = "nebula-fudo"
group = "nebula-fudo"
mode = "0400"

[secrets."gpu-node-tagger.ca-crt"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.ca-crt.age"
target = "/run/gpu-node-tagger/ca.crt"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"

[secrets."gpu-node-tagger.token"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.token.age"
target = "/run/gpu-node-tagger/token"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"
