etypes = [
    "aes128-cts-hmac-sha1-96",
    "aes256-cts-hmac-sha1-96",
]
max_ticket_lifetime = "1w"
max_renewable_lifetime = "1m"
domains = []
kdc_role = "kdc"
trusts = []

[principals."WELLKNOWN/ANONYMOUS@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."WELLKNOWN/FEDERATED@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."WELLKNOWN/org.h5l.fast-cookie@WELLKNOWN:ORG.H5L"]
kind = "infrastructure"

[principals."changepw/kerberos@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."default@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."kadmin/admin@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."kadmin/changepw@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."kadmin/hprop@RUS.SELBY.CA"]
kind = "infrastructure"

[principals."krbtgt/RUS.SELBY.CA@RUS.SELBY.CA"]
kind = "infrastructure"
