[keytab]
source = "keytab.age"
target = "/run/aegis/keytab"
user = "root"
group = "root"
mode = "0600"

[nexus-key]
source = "nexus-key.age"
target = "/run/aegis/nexus-key"
user = "root"
group = "root"
mode = "0400"
type = "ed25519"

[secrets.wallfly-hermes-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-hermes-passwd.age"
target = "/run/wallfly-hermes/passwd"
user = "hermes"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-jasper-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-jasper-passwd.age"
target = "/run/wallfly-jasper/passwd"
user = "jasper"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-ken-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-ken-passwd.age"
target = "/run/wallfly-ken/passwd"
user = "ken"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-niten-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-niten-passwd.age"
target = "/run/wallfly-niten/passwd"
user = "niten"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-openclaw-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-openclaw-passwd.age"
target = "/run/wallfly-openclaw/passwd"
user = "openclaw"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-reaper-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-reaper-passwd.age"
target = "/run/wallfly-reaper/passwd"
user = "reaper"
group = "root"
mode = "0400"
role = "wallfly-seattle"

[secrets.wallfly-xiaoxuan-passwd]
source = "../../roles/wallfly-seattle/secrets/wallfly-xiaoxuan-passwd.age"
target = "/run/wallfly-xiaoxuan/passwd"
user = "xiaoxuan"
group = "root"
mode = "0400"
role = "wallfly-seattle"
