[keytab]
source = "keytab.age"
target = "/run/aegis/keytab"
user = "root"
group = "root"
mode = "0600"

[nexus-key]
source = "nexus-key.age"
target = "/run/aegis/nexus-key"
user = "root"
group = "root"
mode = "0400"
type = "ed25519"
