roles = [
    "domain-burg.fudo.org",
    "site-thecitadel",
]

[[ssh-host-keys]]
source = "ssh/ssh_host_ecdsa_key.age"
target = "ssh_host_ecdsa_key"
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
type = "ecdsa"

[[ssh-host-keys]]
source = "ssh/ssh_host_ed25519_key.age"
target = "ssh_host_ed25519_key"
target_dir = "/run/aegis/ssh"
user = "root"
group = "root"
mode = "0600"
type = "ed25519"

[keytab]
source = "keytab.age"
target = "/run/aegis/keytab"
user = "root"
group = "root"
mode = "0600"

[nexus-key]
source = "nexus-key.age"
target = "/run/aegis/nexus-key"
user = "root"
group = "root"
mode = "0400"
type = "ed25519"

[secrets."gpu-node-tagger.ca-crt"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.ca-crt.age"
target = "/run/gpu-node-tagger/ca.crt"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"

[secrets."gpu-node-tagger.token"]
source = "../../roles/domain-burg.fudo.org/secrets/gpu-node-tagger.token.age"
target = "/run/gpu-node-tagger/token"
user = "root"
group = "root"
mode = "0400"
role = "domain-burg.fudo.org"

[secrets.deploy-ed25519-key]
source = "ssh/deploy_ed25519_key.age"
target = "/run/aegis/ssh/deploy_ed25519_key"
user = "root"
group = "root"
mode = "0600"

[secrets.initrd-ed25519-key]
source = "ssh/initrd_ed25519_key.age"
target = "/run/aegis/ssh/initrd_ed25519_key"
user = "root"
group = "root"
mode = "0600"
