hosts = [
    "cellar",
    "fimbria",
    "forum",
    "grendal",
    "janus",
    "lambda",
    "larder",
    "nostromo",
    "pantry",
    "rama",
    "thing-0",
    "thunk-0",
    "wormhole0",
    "zbox",
]
