hosts = [
    "cartus",
    "cellar",
    "codex",
    "fimbria",
    "fontus",
    "forum",
    "grendal",
    "janus",
    "jazz",
    "lambda",
    "larder",
    "limina",
    "nostromo",
    "rama",
    "rector",
    "system3",
    "system7",
    "thing-0",
    "thing-1",
    "thing-2",
    "thing-3",
    "thing-4",
    "thunk-0",
    "toothless",
    "wormhole0",
    "zbox",
]
