hosts = [
    "germany",
]

[placement."secret:matrix-jwt.pem"]
target = "/run/matrix/jwt.pem"
user = "matrix-synapse"

[placement."secret:matrix-oidc.secret"]
target = "/run/matrix/oidc-client.secret"
user = "matrix-synapse"
