hosts = [
    "limina",
    "jazz",
    "rector",
    "thing-3",
    "thing-4",
    "forge",
    "nomenclator-0",
    "telly",
    "legio-0",
    "legio-1",
    "magis-0",
    "magis-1",
    "system7",
    "cogito-0",
]
