etypes = [
    "aes128-cts-hmac-sha1-96",
    "aes256-cts-hmac-sha1-96",
]
max_ticket_lifetime = "1w"
max_renewable_lifetime = "1m"
domains = [
    "burg.fudo.org",
]
kdc_role = "burg-kdc"
trusts = []

[principals."WELLKNOWN/ANONYMOUS@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."WELLKNOWN/FEDERATED@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."WELLKNOWN/org.h5l.fast-cookie@WELLKNOWN:ORG.H5L"]
kind = "infrastructure"

[principals."changepw/kerberos@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."default@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."host/cogito-0.burg.fudo.org"]
kind = "service"
host = "cogito-0"

[principals."host/forge.burg.fudo.org"]
kind = "service"
host = "forge"

[principals."host/jazz.burg.fudo.org"]
kind = "service"
host = "jazz"

[principals."host/legio-0.burg.fudo.org"]
kind = "service"
host = "legio-0"

[principals."host/legio-1.burg.fudo.org"]
kind = "service"
host = "legio-1"

[principals."host/limina.burg.fudo.org"]
kind = "service"
host = "limina"

[principals."host/magis-0.burg.fudo.org"]
kind = "service"
host = "magis-0"

[principals."host/magis-1.burg.fudo.org"]
kind = "service"
host = "magis-1"

[principals."host/nomenclator-0.burg.fudo.org"]
kind = "service"
host = "nomenclator-0"

[principals."host/rector.burg.fudo.org"]
kind = "service"
host = "rector"

[principals."host/system7.burg.fudo.org"]
kind = "service"
host = "system7"

[principals."host/telly.burg.fudo.org"]
kind = "service"
host = "telly"

[principals."host/thing-3.burg.fudo.org"]
kind = "service"
host = "thing-3"

[principals."host/thing-4.burg.fudo.org"]
kind = "service"
host = "thing-4"

[principals."kadmin/admin@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."kadmin/changepw@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."kadmin/hprop@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."krbtgt/BURG.FUDO.ORG@BURG.FUDO.ORG"]
kind = "infrastructure"

[principals."ssh/cogito-0.burg.fudo.org"]
kind = "service"
host = "cogito-0"

[principals."ssh/forge.burg.fudo.org"]
kind = "service"
host = "forge"

[principals."ssh/jazz.burg.fudo.org"]
kind = "service"
host = "jazz"

[principals."ssh/legio-0.burg.fudo.org"]
kind = "service"
host = "legio-0"

[principals."ssh/legio-1.burg.fudo.org"]
kind = "service"
host = "legio-1"

[principals."ssh/limina.burg.fudo.org"]
kind = "service"
host = "limina"

[principals."ssh/magis-0.burg.fudo.org"]
kind = "service"
host = "magis-0"

[principals."ssh/magis-1.burg.fudo.org"]
kind = "service"
host = "magis-1"

[principals."ssh/nomenclator-0.burg.fudo.org"]
kind = "service"
host = "nomenclator-0"

[principals."ssh/rector.burg.fudo.org"]
kind = "service"
host = "rector"

[principals."ssh/system7.burg.fudo.org"]
kind = "service"
host = "system7"

[principals."ssh/telly.burg.fudo.org"]
kind = "service"
host = "telly"

[principals."ssh/thing-3.burg.fudo.org"]
kind = "service"
host = "thing-3"

[principals."ssh/thing-4.burg.fudo.org"]
kind = "service"
host = "thing-4"
